const listTecnologies = [
    {
        url:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Unofficial_JavaScript_logo_2.svg/800px-Unofficial_JavaScript_logo_2.svg.png',
        name:'Javascript'
    },
    {
        url:'https://www.pragimtech.com/wp-content/uploads/2021/03/ReactJS.jpg',
        name:'ReactJS'
    },
    {
        url:'https://digital55.com/wp-content/uploads/2022/01/Cuando_y_por_que_debo_usar_redux_en_mis_proyectos_frontend.jpg',
        name:'Redux'
    },
    {
        url:'https://www.drupal.org/files/project-images/screenshot_361.png',
        name:'TailwindCSS'
    },
    {
        url:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRb1NpiPKRZbhP_uFuWJ0DcWl64h6mDljJmflR5kBF7DnXfmJ-r6NQVxI8_dlKQBa9fLt0&usqp=CAU',
        name:'ExpressJS'
    },
    {
        url:'https://google.github.io/sqlcommenter/images/sequelize-logo.png',
        name:'Sequelize'
    },
    {
        url:'https://yt3.googleusercontent.com/GsP5Yvc5jOSop4SJf_75wdOYaEbO-7ZyYhnARodAGRnEMh-OQjGPGzUz2ZtzsHPtqFyHGvmbEtI=s900-c-k-c0x00ffffff-no-rj',
        name:'Firebase'
    },
    {
        url:'https://images.g2crowd.com/uploads/product/image/large_detail/large_detail_251be2af3ae607c45c14e816eaa1cf41/postgresql.png',
        name:'PostgreSQL'
    },
    {
        url:'https://www.solucionex.com/sites/default/files/posts/imagen/git.jpg',
        name:'Git'
    },
    {
        url:'https://plugins.jetbrains.com/files/14097/165316/icon/pluginIcon.png',
        name:'Markdown'
    }
]

export default listTecnologies;